pull_request_rules:
    - name: automatic merge for Dependabot pull requests
      conditions:
          - author=dependabot[bot]
          - status-success=bundlesize
          - status-success=Travis CI - Pull Request
      actions:
          merge:
              method: merge
    - name: merge when all requested reviews are valid
      conditions:
          - status-success=Travis CI - Pull Request
          - status-success=bundlesize
          - '#approved-reviews-by>=1'
          - '#changes-requested-reviews-by=0'
          - '#commented-reviews-by=0'
          - label!=do not merge
      actions:
          merge:
              method: squash
              strict: true
