pull_request_rules:
    - name: automatic merge for Dependabot pull requests
      conditions:
          - author=dependabot[bot]
          - "status-success=Code scanning - action / CodeQL-Build (pull_request)"
          - "status-success=JS-API / build and lint (pull_request)"
          - "status-success=JS-API / test (pull_request)"
          - "status-success=JS-API / release"
      actions:
        merge:
            method: squash

    - name: merge when all requested reviews are valid
      conditions:
          - "status-success=Code scanning - action / CodeQL-Build (pull_request)"
          - "status-success=JS-API / build and lint (pull_request)"
          - "status-success=JS-API / test (pull_request)"
          - "status-success=JS-API / release"
          - '#approved-reviews-by>=1'
          - '#changes-requested-reviews-by=0'
          - '#commented-reviews-by=0'
          - label!=do not merge
      actions:
        merge:
            method: squash
