/**
 * Alfresco Content Services REST API
 * **Authentication API**  Provides access to the authentication features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../../../alfrescoApiClient', './ValidTicket'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../../../alfrescoApiClient'), require('./ValidTicket'));
  } else {
    // Browser globals (root is window)
    if (!root.AlfrescoAuthRestApi) {
      root.AlfrescoAuthRestApi = {};
    }
    root.AlfrescoAuthRestApi.ValidTicketEntry = factory(root.AlfrescoAuthRestApi.ApiClient, root.AlfrescoAuthRestApi.ValidTicket);
  }
}(this, function(ApiClient, ValidTicket) {
  'use strict';




  /**
   * The ValidTicketEntry model module.
   * @module model/ValidTicketEntry
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ValidTicketEntry</code>.
   * @alias module:model/ValidTicketEntry
   * @class
   * @param entry {module:model/ValidTicket}
   */
  var exports = function(entry) {
    var _this = this;

    _this['entry'] = entry;
  };

  /**
   * Constructs a <code>ValidTicketEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValidTicketEntry} obj Optional instance to populate.
   * @return {module:model/ValidTicketEntry} The populated <code>ValidTicketEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('entry')) {
        obj['entry'] = ValidTicket.constructFromObject(data['entry']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ValidTicket} entry
   */
  exports.prototype['entry'] = undefined;



  return exports;
}));


