/**
 * Alfresco Content Services REST API
 * **Search API**  Provides access to the search features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../../../alfrescoApiClient', '../model/ResultSetContextBuckets'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../../../alfrescoApiClient'), require('./ResultSetContextBuckets'));
  } else {
    // Browser globals (root is window)
    if (!root.AlfrescoContentServicesRestApi) {
      root.AlfrescoContentServicesRestApi = {};
    }
    root.AlfrescoContentServicesRestApi.ResultSetContextFacetFields = factory(root.AlfrescoContentServicesRestApi.ApiClient, root.AlfrescoContentServicesRestApi.ResultSetContextBuckets);
  }
}(this, function(ApiClient, ResultSetContextBuckets) {
  'use strict';




  /**
   * The ResultSetContextFacetFields model module.
   * @module model/ResultSetContextFacetFields
   * @version 1
   */

  /**
   * Constructs a new <code>ResultSetContextFacetFields</code>.
   * @alias module:model/ResultSetContextFacetFields
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ResultSetContextFacetFields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResultSetContextFacetFields} obj Optional instance to populate.
   * @return {module:model/ResultSetContextFacetFields} The populated <code>ResultSetContextFacetFields</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('buckets')) {
        obj['buckets'] = ApiClient.convertToType(data['buckets'], [ResultSetContextBuckets]);
      }
    }
    return obj;
  }

  /**
   * The field name or its explicit label, if provided on the request
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * An array of buckets and values
   * @member {Array.<module:model/ResultSetContextBuckets>} buckets
   */
  exports.prototype['buckets'] = undefined;



  return exports;
}));


