/**
 * Alfresco Content Services REST API
 * **Search API**  Provides access to the search features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../../../alfrescoApiClient', '../model/ResponseConsistency', '../model/ResultSetContextFacetFields', '../model/ResultSetContextFacetQueries', '../model/ResultSetContextSpellcheck'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../../../alfrescoApiClient'), require('./ResponseConsistency'), require('./ResultSetContextFacetFields'), require('./ResultSetContextFacetQueries'), require('./ResultSetContextSpellcheck'));
  } else {
    // Browser globals (root is window)
    if (!root.AlfrescoContentServicesRestApi) {
      root.AlfrescoContentServicesRestApi = {};
    }
    root.AlfrescoContentServicesRestApi.ResultSetContext = factory(root.AlfrescoContentServicesRestApi.ApiClient, root.AlfrescoContentServicesRestApi.ResponseConsistency, root.AlfrescoContentServicesRestApi.ResultSetContextFacetFields, root.AlfrescoContentServicesRestApi.ResultSetContextFacetQueries, root.AlfrescoContentServicesRestApi.ResultSetContextSpellcheck);
  }
}(this, function(ApiClient, ResponseConsistency, ResultSetContextFacetFields, ResultSetContextFacetQueries, ResultSetContextSpellcheck) {
  'use strict';




  /**
   * The ResultSetContext model module.
   * @module model/ResultSetContext
   * @version 1
   */

  /**
   * Constructs a new <code>ResultSetContext</code>.
   * Context that applies to the whole result set
   * @alias module:model/ResultSetContext
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ResultSetContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResultSetContext} obj Optional instance to populate.
   * @return {module:model/ResultSetContext} The populated <code>ResultSetContext</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('consistency')) {
        obj['consistency'] = ResponseConsistency.constructFromObject(data['consistency']);
      }
      if (data.hasOwnProperty('facetQueries')) {
        obj['facetQueries'] = ApiClient.convertToType(data['facetQueries'], [ResultSetContextFacetQueries]);
      }
      if (data.hasOwnProperty('facetFields')) {
        obj['facetFields'] = ApiClient.convertToType(data['facetFields'], [ResultSetContextFacetFields]);
      }
      if (data.hasOwnProperty('spellcheck')) {
        obj['spellcheck'] = ApiClient.convertToType(data['spellcheck'], [ResultSetContextSpellcheck]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ResponseConsistency} consistency
   */
  exports.prototype['consistency'] = undefined;
  /**
   * The counts from facet queries
   * @member {Array.<module:model/ResultSetContextFacetQueries>} facetQueries
   */
  exports.prototype['facetQueries'] = undefined;
  /**
   * The counts from field facets
   * @member {Array.<module:model/ResultSetContextFacetFields>} facetFields
   */
  exports.prototype['facetFields'] = undefined;
  /**
   * Suggested corrections  If zero results were found for the original query then a single entry of type \"searchInsteadFor\" will be returned. If alternatives were found that return more results than the original query they are returned as \"didYouMean\" options. The highest quality suggestion is first.
   * @member {Array.<module:model/ResultSetContextSpellcheck>} spellcheck
   */
  exports.prototype['spellcheck'] = undefined;



  return exports;
}));


