/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', './PermissionElement'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PermissionElement'));
  } else {
    // Browser globals (root is window)
    if (!root.AlfrescoCoreRestApi) {
      root.AlfrescoCoreRestApi = {};
    }
    root.AlfrescoCoreRestApi.PermissionsBodyUpdate = factory(root.AlfrescoCoreRestApi.ApiClient, root.AlfrescoCoreRestApi.PermissionElement);
  }
}(this, function(ApiClient, PermissionElement) {
  'use strict';




  /**
   * The PermissionsBodyUpdate model module.
   * @module model/PermissionsBodyUpdate
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>PermissionsBodyUpdate</code>.
   * @alias module:model/PermissionsBodyUpdate
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PermissionsBodyUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionsBodyUpdate} obj Optional instance to populate.
   * @return {module:model/PermissionsBodyUpdate} The populated <code>PermissionsBodyUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('isInheritanceEnabled')) {
        obj['isInheritanceEnabled'] = ApiClient.convertToType(data['isInheritanceEnabled'], 'Boolean');
      }
      if (data.hasOwnProperty('locallySet')) {
        obj['locallySet'] = ApiClient.convertToType(data['locallySet'], [PermissionElement]);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} isInheritanceEnabled
   */
  exports.prototype['isInheritanceEnabled'] = undefined;
  /**
   * @member {Array.<module:model/PermissionElement>} locallySet
   */
  exports.prototype['locallySet'] = undefined;



  return exports;
}));


