/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AlfrescoCoreRestApi) {
      root.AlfrescoCoreRestApi = {};
    }
    root.AlfrescoCoreRestApi.SiteMembershipBodyUpdate = factory(root.AlfrescoCoreRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SiteMembershipBodyUpdate model module.
   * @module model/SiteMembershipBodyUpdate
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SiteMembershipBodyUpdate</code>.
   * @alias module:model/SiteMembershipBodyUpdate
   * @class
   * @param role {module:model/SiteMembershipBodyUpdate.RoleEnum}
   */
  var exports = function(role) {
    var _this = this;

    _this['role'] = role;
  };

  /**
   * Constructs a <code>SiteMembershipBodyUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SiteMembershipBodyUpdate} obj Optional instance to populate.
   * @return {module:model/SiteMembershipBodyUpdate} The populated <code>SiteMembershipBodyUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SiteMembershipBodyUpdate.RoleEnum} role
   */
  exports.prototype['role'] = undefined;


  /**
   * Allowed values for the <code>role</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RoleEnum = {
    /**
     * value: "SiteConsumer"
     * @const
     */
    "SiteConsumer": "SiteConsumer",
    /**
     * value: "SiteCollaborator"
     * @const
     */
    "SiteCollaborator": "SiteCollaborator",
    /**
     * value: "SiteContributor"
     * @const
     */
    "SiteContributor": "SiteContributor",
    /**
     * value: "SiteManager"
     * @const
     */
    "SiteManager": "SiteManager"  };


  return exports;
}));


