/**
 * Alfresco Content Services REST API
 * **Search API**  Provides access to the search features of Alfresco Content Services.
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../../../alfrescoApiClient', '../model/ResultBucketsBuckets'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../../../alfrescoApiClient'), require('./ResultBucketsBuckets'));
  } else {
    // Browser globals (root is window)
    if (!root.AlfrescoContentServicesRestApi) {
      root.AlfrescoContentServicesRestApi = {};
    }
    root.AlfrescoContentServicesRestApi.ResultBuckets = factory(root.AlfrescoContentServicesRestApi.ApiClient, root.AlfrescoContentServicesRestApi.ResultBucketsBuckets);
  }
}(this, function(ApiClient, ResultBucketsBuckets) {
  'use strict';




  /**
   * The ResultBuckets model module.
   * @module model/ResultBuckets
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>ResultBuckets</code>.
   * @alias module:model/ResultBuckets
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ResultBuckets</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {any} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResultBuckets} obj Optional instance to populate.
   * @return {module:model/ResultBuckets} The populated <code>ResultBuckets</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('buckets')) {
        obj['buckets'] = ApiClient.convertToType(data['buckets'], [ResultBucketsBuckets]);
      }
    }
    return obj;
  }

  /**
   * The field name or its explicit label, if provided on the request
   * @member {string} label
   */
  exports.prototype['label'] = undefined;
  /**
   * An array of buckets and values
   * @member {module:model/ResultBucketsBuckets[]} buckets
   */
  exports.prototype['buckets'] = undefined;



  return exports;
}));


