/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlfrescoCoreRestApi);
  }
}(this, function(expect, AlfrescoCoreRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlfrescoCoreRestApi.Activity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Activity', function() {
    it('should create an instance of Activity', function() {
      // uncomment below and update the code to test Activity
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be.a(AlfrescoCoreRestApi.Activity);
    });

    it('should have the property postPersonId (base name: "postPersonId")', function() {
      // uncomment below and update the code to test the property postPersonId
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

    it('should have the property siteId (base name: "siteId")', function() {
      // uncomment below and update the code to test the property siteId
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

    it('should have the property postedAt (base name: "postedAt")', function() {
      // uncomment below and update the code to test the property postedAt
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

    it('should have the property feedPersonId (base name: "feedPersonId")', function() {
      // uncomment below and update the code to test the property feedPersonId
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

    it('should have the property activitySummary (base name: "activitySummary")', function() {
      // uncomment below and update the code to test the property activitySummary
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

    it('should have the property activityType (base name: "activityType")', function() {
      // uncomment below and update the code to test the property activityType
      //var instane = new AlfrescoCoreRestApi.Activity();
      //expect(instance).to.be();
    });

  });

}));
