/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlfrescoCoreRestApi);
  }
}(this, function(expect, AlfrescoCoreRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlfrescoCoreRestApi.Node();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Node', function() {
    it('should create an instance of Node', function() {
      // uncomment below and update the code to test Node
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be.a(AlfrescoCoreRestApi.Node);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property nodeType (base name: "nodeType")', function() {
      // uncomment below and update the code to test the property nodeType
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property isFolder (base name: "isFolder")', function() {
      // uncomment below and update the code to test the property isFolder
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property isFile (base name: "isFile")', function() {
      // uncomment below and update the code to test the property isFile
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property isLocked (base name: "isLocked")', function() {
      // uncomment below and update the code to test the property isLocked
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property modifiedAt (base name: "modifiedAt")', function() {
      // uncomment below and update the code to test the property modifiedAt
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property modifiedByUser (base name: "modifiedByUser")', function() {
      // uncomment below and update the code to test the property modifiedByUser
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property createdByUser (base name: "createdByUser")', function() {
      // uncomment below and update the code to test the property createdByUser
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parentId")', function() {
      // uncomment below and update the code to test the property parentId
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property isLink (base name: "isLink")', function() {
      // uncomment below and update the code to test the property isLink
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property aspectNames (base name: "aspectNames")', function() {
      // uncomment below and update the code to test the property aspectNames
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property properties (base name: "properties")', function() {
      // uncomment below and update the code to test the property properties
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property allowableOperations (base name: "allowableOperations")', function() {
      // uncomment below and update the code to test the property allowableOperations
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

    it('should have the property permissions (base name: "permissions")', function() {
      // uncomment below and update the code to test the property permissions
      //var instane = new AlfrescoCoreRestApi.Node();
      //expect(instance).to.be();
    });

  });

}));
