/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlfrescoCoreRestApi);
  }
}(this, function(expect, AlfrescoCoreRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlfrescoCoreRestApi.FavoritesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FavoritesApi', function() {
    describe('createFavorite', function() {
      it('should call createFavorite successfully', function(done) {
        //uncomment below and update the code to test createFavorite
        //instance.createFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSiteFavorite', function() {
      it('should call createSiteFavorite successfully', function(done) {
        //uncomment below and update the code to test createSiteFavorite
        //instance.createSiteFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFavorite', function() {
      it('should call deleteFavorite successfully', function(done) {
        //uncomment below and update the code to test deleteFavorite
        //instance.deleteFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSiteFavorite', function() {
      it('should call deleteSiteFavorite successfully', function(done) {
        //uncomment below and update the code to test deleteSiteFavorite
        //instance.deleteSiteFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavorite', function() {
      it('should call getFavorite successfully', function(done) {
        //uncomment below and update the code to test getFavorite
        //instance.getFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoriteSite', function() {
      it('should call getFavoriteSite successfully', function(done) {
        //uncomment below and update the code to test getFavoriteSite
        //instance.getFavoriteSite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFavoriteSitesForPerson', function() {
      it('should call listFavoriteSitesForPerson successfully', function(done) {
        //uncomment below and update the code to test listFavoriteSitesForPerson
        //instance.listFavoriteSitesForPerson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFavorites', function() {
      it('should call listFavorites successfully', function(done) {
        //uncomment below and update the code to test listFavorites
        //instance.listFavorites(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
