/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlfrescoCoreRestApi);
  }
}(this, function(expect, AlfrescoCoreRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlfrescoCoreRestApi.SharedlinksApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SharedlinksApi', function() {
    describe('createSharedLink', function() {
      it('should call createSharedLink successfully', function(done) {
        //uncomment below and update the code to test createSharedLink
        //instance.createSharedLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSharedLink', function() {
      it('should call deleteSharedLink successfully', function(done) {
        //uncomment below and update the code to test deleteSharedLink
        //instance.deleteSharedLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('emailSharedLink', function() {
      it('should call emailSharedLink successfully', function(done) {
        //uncomment below and update the code to test emailSharedLink
        //instance.emailSharedLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSharedLink', function() {
      it('should call getSharedLink successfully', function(done) {
        //uncomment below and update the code to test getSharedLink
        //instance.getSharedLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSharedLinkContent', function() {
      it('should call getSharedLinkContent successfully', function(done) {
        //uncomment below and update the code to test getSharedLinkContent
        //instance.getSharedLinkContent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSharedLinkRendition', function() {
      it('should call getSharedLinkRendition successfully', function(done) {
        //uncomment below and update the code to test getSharedLinkRendition
        //instance.getSharedLinkRendition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSharedLinkRenditionContent', function() {
      it('should call getSharedLinkRenditionContent successfully', function(done) {
        //uncomment below and update the code to test getSharedLinkRenditionContent
        //instance.getSharedLinkRenditionContent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSharedLinkRenditions', function() {
      it('should call listSharedLinkRenditions successfully', function(done) {
        //uncomment below and update the code to test listSharedLinkRenditions
        //instance.listSharedLinkRenditions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSharedLinks', function() {
      it('should call listSharedLinks successfully', function(done) {
        //uncomment below and update the code to test listSharedLinks
        //instance.listSharedLinks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
