/**
 * Alfresco Content Services REST API
 * **Authentication API**  Provides access to the authentication features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AlfrescoAuthRestApi);
  }
}(this, function(expect, AlfrescoAuthRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AlfrescoAuthRestApi.AuthenticationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthenticationApi', function() {
    describe('createTicket', function() {
      it('should call createTicket successfully', function(done) {
        //uncomment below and update the code to test createTicket
        //instance.createTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicket', function() {
      it('should call deleteTicket successfully', function(done) {
        //uncomment below and update the code to test deleteTicket
        //instance.deleteTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validateTicket', function() {
      it('should call validateTicket successfully', function(done) {
        //uncomment below and update the code to test validateTicket
        //instance.validateTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
