name: "JS-API"
on:
    push:
        branches:
            - master
            - develop
            - /.*beta.*/
    pull_request:
        branches:
            - develop
    schedule:
        - cron: '0 3 * * *' # At 03:00 AM nightly every day

env:
    GITHUB_REPO_SLUG: ${{ github.repository }}
    GITHUB_BRANCH: ${{ github.ref }}
    GITHUB_PULL_REQUEST: ${{ github.event.number }}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}

jobs:
    build:
        name: "build and lint"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'

            - run: npm ci

            - name: Lint
              run: |
                ./scripts/lint.sh

            - name: Build
              run: |
                ./scripts/build.sh || exit 1

    test:
        needs: build
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'
            - run: npm ci

            - name: Unit test
              shell: bash
              run: |
                npm run test || exit 1
                npm run coverage

            - name: Performance
              shell: bash
              run: ./scripts/test-performance.sh || exit 1

            - name: Integration
              env:
                HOST: ${{ secrets.HOST }}
                USERNAME: ${{ secrets.USERNAME }}
                PASSWORD: ${{ secrets.PASSWORD }}
              shell: bash
              run: ./scripts/test-integration.sh || exit 1

    release:
        needs: test
        name: release
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event.schedule == '0 3 * * *'
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'
            - run: npm ci

            - name: Release Build
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              shell: bash
              run: |
                  ./scripts/build.sh || exit 1

            - uses: actions/setup-node@v3
              name: Release library Npm registry
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              with:
                node-version: 16
                registry-url: 'https://${{ vars.NPM_REGISTRY_ADDRESS }}'
                scope: '@alfresco'
            - run: ./scripts/publish.sh
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

            - uses: actions/setup-node@v3
              name: Release library GH registry
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              with:
                node-version: 16
                registry-url: 'https://npm.pkg.github.com'
                scope: '@alfresco'
            - run: ./scripts/publish.sh
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Get tag from package.json
                if: github.ref == 'refs/heads/master'
                id: getTag
                uses: actions/github-script@v6
                with:
                    script: |
                        const newTag = require('./package.json').version;
                        core.setOutput('newTag', newTag);

            -   name: Create new tag on Github
                if: github.ref == 'refs/heads/master'
                run: |
                    echo "Creating a new tag: ${{ steps.getTag.outputs.newTag }}"
                    git config --local user.name "alfresco-build"
                    git config --local user.email "build@alfresco.com"
                    git tag -a ${{ steps.getTag.outputs.newTag }} -m "${{ steps.getTag.outputs.newTag }} [ci skip] "
                    git remote rm origin
                    GITHUB_REPO=https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/Alfresco/alfresco-js-api.git
                    git remote add origin $GITHUB_REPO
                    git push origin --tags
