name: "JS-API"
on:
    push:
        branches:
            - master
            - develop
            - /.*beta.*/
    pull_request:
        branches:
            - develop
    schedule:
        - cron: '0 3 * * *' # At 03:00 AM nightly every day

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    GITHUB_REPO_SLUG: ${{ github.repository }}
    GITHUB_BRANCH: ${{ github.ref }}
    GITHUB_PULL_REQUEST: ${{ github.event.number }}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}

jobs:
    pre-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - name: Ensure SHA pinned actions
              uses: zgosalvez/github-actions-ensure-sha-pinned-actions@b35f285b9bb7e80de0967367cee66d3b6d50ceca # v3.0.1
    build:
        needs: pre-checks
        name: "Build and Lint"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
              with:
                fetch-depth: 2

            - name: node
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build
              run: |
                ./scripts/build.sh || exit 1

    test:
        needs: build
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Unit test
              shell: bash
              run: npm test

    release:
        needs: [test]
        name: release
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event.schedule == '0 3 * * *'
        steps:
            - name: Checkout
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Release Build
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              shell: bash
              run: |
                  ./scripts/build.sh || exit 1

            - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              name: Release library Npm registry
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
                registry-url: 'https://${{ vars.NPM_REGISTRY_ADDRESS }}'
                scope: '@alfresco'
            - run: ./scripts/publish.sh
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

            - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              name: Release library GH registry
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
                registry-url: 'https://npm.pkg.github.com'
                scope: '@alfresco'
            - run: ./scripts/publish.sh
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Release Tag
              if: github.ref == 'refs/heads/master'
              uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
              with:
                github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
                script: |
                    const createTag = require('./scripts/create-tag.js');
                    await createTag({github, context});
