name: "JS-API"
on:
    push:
        branches:
            - master
            - develop
            - /.*beta.*/
    pull_request:
        branches:
            - develop

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    GITHUB_REPO_SLUG: ${{ github.repository }}
    GITHUB_BRANCH: ${{ github.ref }}
    GITHUB_PULL_REQUEST: ${{ github.event.number }}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}

jobs:
    build:
        name: "Build and Lint"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: node
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build
              run: |
                ./scripts/build.sh || exit 1

    test:
        needs: build
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Unit test
              shell: bash
              run: npm test
