name: "JS-API"
on:
    push:
        branches:
            - master
            - develop
            - /.*beta.*/
    pull_request:
        branches:
            - develop
    schedule:
        - cron: '0 3 * * *' # At 03:00 AM nightly every day

env:
    GITHUB_REPO_SLUG: ${{ github.repository }}
    GITHUB_BRANCH: ${{ github.ref }}
    GITHUB_PULL_REQUEST: ${{ github.event.number }}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}

jobs:
    build:
        name: "Build and Lint"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Lint
              run: |
                ./scripts/lint.sh

            - name: Build
              run: |
                ./scripts/build.sh || exit 1

    test:
        needs: build
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Unit test
              shell: bash
              run: |
                npm run test || exit 1
                npm run coverage

    test-performance:
        needs: build
        name: Performance Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Performance
              shell: bash
              run: ./scripts/test-performance.sh || exit 1

    test-integration:
        needs: build
        name: Integration Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Integration Tests
              env:
                HOST: ${{ secrets.HOST }}
                USERNAME: ${{ secrets.USERNAME }}
                PASSWORD: ${{ secrets.PASSWORD }}
              shell: bash
              run: ./scripts/test-integration.sh || exit 1

    release:
        needs: [test, test-integration, test-performance]
        name: release
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event.schedule == '0 3 * * *'
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Release Build
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              shell: bash
              run: |
                  ./scripts/build.sh || exit 1

            - uses: actions/setup-node@v3
              name: Release library Npm registry
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              with:
                node-version: 16
                registry-url: 'https://${{ vars.NPM_REGISTRY_ADDRESS }}'
                scope: '@alfresco'
            - run: ./scripts/publish.sh
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

            - uses: actions/setup-node@v3
              name: Release library GH registry
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              with:
                node-version: 16
                registry-url: 'https://npm.pkg.github.com'
                scope: '@alfresco'
            - run: ./scripts/publish.sh
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Release Tag
              if: github.ref == 'refs/heads/master'
              shell: bash
              run: |
                  ./scripts/git-tag.sh
